  GNU nano 8.4                  /etc/asterisk/pjsip.conf
[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.pem
priv_key_file=/etc/asterisk/keys/asterisk.key
method=tlsv1_2

; --- Utilisateur 100 ---
[100]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=100
aors=100
transport=transport-tls
media_encryption=sdes
rewrite_contact=yes

[100]
type=auth
auth_type=userpass
password=MotDePasse100
username=100

[100]
type=aor
max_contacts=1

; --- Utilisateur 200 ---
[200]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=200
aors=200
transport=transport-tls
media_encryption=sdes
rewrite_contact=yes

[200]
type=auth
auth_type=userpass
password=MotDePasse200
username=200

[200]
type=aor
max_contacts=1
